#!/usr/bin/bash
# swaylock \
# --image "~/Pictures/wallpapers/background.jpg" \
# --indicator-caps-lock \
# --inside-wrong-color f38ba8  \
# --ring-wrong-color 161925  \
# --inside-clear-color a6e3a1 \
# --ring-clear-color 161925 \
# --inside-ver-color 89b4fa \
# --ring-ver-color 161925 \
# --text-color  f5c2e7 \
# --indicator-radius 100 \
# --indicator-thickness 5 \
# --ring-color 161925 \
# --key-hl-color f5c2e7 \
# --line-color 313244 \
# --inside-color 00161925 \
# --separator-color 00000000 &
swaylock \
	--screenshots \
	--clock \
	--indicator \
	--indicator-radius 100 \
	--indicator-thickness 5 \
	--effect-blur 8x5 \
	--effect-vignette 0.4:0.4 \
	--key-hl-color f5c2e7 \
	--line-color 313244 \
	--inside-color 00161925 \
    --inside-wrong-color f38ba8  \
    --inside-clear-color a6e3a1 \
    --inside-ver-color 89b4fa \
    --ring-color 161925 \
    --ring-wrong-color 161925  \
    --ring-clear-color 161925 \
    --ring-ver-color 161925 \
    --text-color  f5c2e7 \
	--separator-color 00000000 \
	--fade-in 0.2 &

# sleep 2; ~/.config/hypr/scripts/screenshot_full